
<hr/>
<p><a href="http://plugingarden.com/wordpress-gallery-plugin/?src=wpeg" target="_blank"><strong>WP Easy Gallery Pro</strong></a><br /><span>Pro Features include: Multi-image uploader, Enhanced admin section for easier navigation, Image preview pop-up, and more...</span></p>
<p><a href="http://plugingarden.com/wordpress-gallery-plugin/?src=wpeg" target="_blank"><img title="WP-Easy-Gallery-Pro_468x88" src="<?php echo plugins_url( '/images/WP-Easy-Gallery-Pro_468x88.gif', __FILE__ ); ?>" alt="" width="468" height="88" /></a></p>
<!--<p><strong>Custom Post Donations Premium</strong><br /><span class="italics">This WordPress plugin will allow you to create unique customized PayPal donation widgets to insert into your WordPress posts or pages and accept donations. Features include: Multiple Currencies, Multiple PayPal accounts, Custom donation form display titles, and more.</span></p>
<p><a href="http://plugingarden.com/wordpress-paypal-plugin/?src=wpeg"><img src="<?php echo plugins_url( '/images/CustomPostDonationsPro-Banner.gif', __FILE__ ); ?>" width="400" height="60" alt="Custom Post Donations Pro" /></a></p>
<p><strong>ReFlex Gallery</strong><br /><span class="italics">A fully responsive WordPress image gallery plugin that is actually two galleries in one.</span><br />
<a href="https://wordpress.org/plugins/reflex-gallery/" target="_blank">ReFlex Gallery</a></p>
<p><strong>Email Obfuscate</strong><br /><span class="italics">Email Obfuscate is a Lightweight WordPress/jQuery plugin that prevents spam-bots from harvesting your email addresses by dynamically obfuscating email addresses on your site.</span><br /><a href="http://codecanyon.net/item/wordpressjquery-email-obfuscate-plugin/721738?ref=HahnCreativeGroup" target="_blank">Email Obfuscate Plugin</a></p>
<p><a href="http://codecanyon.net/item/wordpressjquery-email-obfuscate-plugin/721738?ref=HahnCreativeGroup" target="_blank"><img alt="WordPress/jQuery Email Obfuscate Plugin - CodeCanyon Item for Sale" border="0" height="80" src="<?php echo plugins_url( '/images/WordPress-Email-Obfuscate_thumb_80x80.jpg', __FILE__ ); ?>" title="" width="80"></a></p>
<br />-->
<p><span>Please consider making a donatation for the continued development of this plugin. Thanks.</span></p>
<p><a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&amp;hosted_button_id=PMZ2FPNJPH59U" target="_blank"><img src="<?php echo plugins_url( '/images/btn_donateCC_LG.gif', __FILE__ ); ?>" alt="PayPal - The safer, easier way to pay online!"><img alt="" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1"></a></p>